HomeoPathicMang/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('managment.urls')),
    path('',include('account.urls'))
]

account/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('sighin/',views.sighinuser, name='sighinuser'),
    path('login/',views.loginuser, name='loginuser'),
    path('logout/',views.logoutuser, name='logoutuser')
]

managment/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.home, name='home'),
    path('patinet_form/',views.patinet_form, name='patinet_form'),
    path('patient_view/',views.patient_view, name='patient_view'),
    path('search/',views.search,name='search'),
    path('create/',views.Create, name='Create'),
    path('history/',views.history, name='history')
]

account/models.py
from django.db import models

# Create your models here.

managment/models.py
from django.db import models
from django.contrib.auth.models import User

class Patient_info(models.Model):
    name = models.CharField(max_length=55)
    age = models.IntegerField()
    address = models.TextField()
    phone = models.CharField(max_length=11)
    email = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.name

class Treatment(models.Model):
    add_treat = models.TextField(blank=True)
    created_at =models.DateTimeField(auto_now_add=True)
    user= models.ForeignKey(User,on_delete=models.CASCADE)

class History(models.Model):
    add_history = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

managment/forms.py
from django.forms import ModelForm
from .models import *

class PatientForm(ModelForm):
    class Meta:
        model = Patient_info
        fields = ['name','age','address','phone','email']

class TreatmentForm(ModelForm):
    class Meta:
        model = Treatment
        fields = ['add_treat']


class HistoryForm(ModelForm):
    class Meta:
        model = History
        fields = ['add_history']

account/views.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.db import IntegrityError
# Create your views here.
def sighinuser(request):
    if request.method == 'GET':
        user = User.objects.all().count()+1
        return render(request, 'acc/sighin.html',{'form':UserCreationForm,'user':user})
    else:
        if request.POST['password1']==request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], password = request.POST['password1'])
                user.save()
                login(request, user)
                user = User.objects.all().count()
                return redirect('Create')
            except IntegrityError:
                return render(request, 'acc/sighin.html',{'form':UserCreationForm,'user':user, 'error':'Username alreaady been taken plz try anather...!'})
        else:
            user = User.objects.all().count()
            return render(request, 'acc/sighin.html',{'form':UserCreationForm,'user':user,  'error':'password need to be matched.....!'})
   


def loginuser(request):
    if request.method == 'GET':
        return render(request, 'acc/login.html',{'form':AuthenticationForm()})
    else:
        try:
            user = authenticate(request,username= request.POST['username'], password = request.POST['password'])
            if user is None:
                return render(request, 'acc/login.html',{'form':AuthenticationForm(), 'error':'Username and password in not Valid plz try valid Username and Password'})
            else:
                login(request, user)
                return redirect('patient_view')
        except ValueError:
            return render(request, 'acc/login.html',{'form':AuthenticationForm(),'error':'fill the blank field'})

def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')




        

managment/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.db.models import Q
from django.contrib import messages
from .forms import PatientForm,TreatmentForm, HistoryForm

# Create your views here.
def home(request):
    return render(request, 'manag/home.html')

def Create(request):
    if request.method == 'GET':
        return render(request, 'manag/create.html',{'form':PatientForm})
    else:
        form = PatientForm(request.POST)
        nForm = form.save(commit=False)
        nForm.user = request.user
        nForm.save()
        return redirect('patient_view')

def patinet_form(request):
    if request.method =='POST':
        name = request.POST.get('name')
        age = request.POST.get('age')
        address = request.POST.get('address')
        phone =  request.POST.get('phone')
        email = request.POST.get('email')
        forms = Patient_info(name=name,age=age, address=address,phone=phone,email=email)
        forms.save()
        return render(request, 'manag/patient_view.html')
    else:
        return render(request, 'manag/patinet_form.html')

def patient_view(request):
    data = Treatment.objects.filter(user=request.user)
    pdata = Patient_info.objects.filter(user=request.user)
    if request.method == 'GET':
        return render(request, 'manag/patient_view.html',{'form':TreatmentForm(),'trt':data,'data':pdata})
    else:
        tform = TreatmentForm(request.POST)
        ntform = tform.save(commit=False)
        ntform.user = request.user
        ntform.save()
        return render(request, 'manag/patient_view.html',{'form':TreatmentForm(),'trt':data,'pdata':pdata})    

def search(request):
    if request.method == 'POST':
        srch = request.POST['srch']
        if srch:
            match = Patient_info.objects.filter(Q(id__icontains = srch)|
                                               Q(name__icontains = srch)|
                                               Q(address__icontains = srch)
                                               )
            if match:
                return render(request,'manag/search.html', {'sr':match})
            else:
                messages.error(request,'no result found....!')
        else:
            return HttpRessponseRedirect('/search/')

    return render(request, 'manag/search.html')

def history(request):
    data = History.objects.filter(user=request.user)
    if request.method == 'GET':
        return render(request, 'manag/history.html',{'form':HistoryForm(), 'data':data})
    else:
        tform = HistoryForm(request.POST)
        ntform = tform.save(commit=False)
        ntform.user = request.user
        ntform.save()
        data = History.objects.filter(user=request.user)
        return render(request,'manag/history.html',{'form':HistoryForm(), 'data':data})

HomeoPathicMang/templates/base.html
<html>
    {% load static %}
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
 
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'CSS/style.css' %}">
        <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    </head>
    <body>
        <div >
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
                <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}"><b>HomeoPathic</b></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse " id="navbarSupportedContent">
                    <ul class="navbar-nav  ml-auto">
                        {% if user.is_authenticated %}
                        
                        <li class="nav-item active">
                            <a class="nav-link" href="javascript:{document.getElementById('logout').submit()}">Logout<span class="sr-only">(current)</span></a>
                            <form id="logout" method="POST" action="{% url 'logoutuser' %}">
                                {% csrf_token %}
                                <input type="hidden" />  
                            </form>
                        </li>
                        <i class="fa fa-sign-out" aria-hidden="true"></i>
                        {% else  %}
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'sighinuser' %}">SignIn <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'loginuser' %}">Login <span class="sr-only">(current)</span></a>
                            </li>

                        {% endif %}
                  </ul>
               
            </nav>
           <br>
           <br>
           <br>
           
                            
            {% block content %}

            {% endblock %}
        </div>
    </body>
</html>

account/templates/acc/login.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="hdr">
        <h2>Login</h2>
    </div>
    <form method="POST">
        {% csrf_token %}
        <div class="log">
            <lable>Username &nbsp&nbsp</lable>
            <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username">
            <br><br>
            <lable>Password &nbsp&nbsp</lable> 
            <input type="password" name="password" autocomplete="current-password" required="" id="id_password">
            <br>
            <br>
            <div class="log-btn">
                <button type="submit">Login</button>
            </div>
            <div class="error">
                <h4>{{ error }}</h4>
            </div>
        </div>
    </form>
</div>

{% endblock %}

account/templates/acc/sighin.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h3>Uptoo id :- {{ user }}</h3>
    <div class="container">
        <div class="sign-hdr">
            <h1>SignIn</h1>
        </div>     
        <div class="sign">   
            <form method="POST">
                {% csrf_token %}
                <div>
                    <lable>Username </lable>&nbsp;&nbsp;
                    
                    <input type="text" name="username" maxlength="150"
                     autocapitalize="none" autocomplete="username" autofocus="" required="" id="id_username">
                   
                </div>
                <br>
                <div>
                    <lable>Password </lable>&nbsp;&nbsp;
                    <input type="password" name="password1" autocomplete="new-password" required="" id="id_password1">
                </div>
                <br>
                <div>
                    <lable>Confirm Password </lable>&nbsp;&nbsp;
                    <input type="password" name="password2" autocomplete="new-password" required="" id="id_password2">
                </div>
                <br>
                <br>
                <div class="sign-btn">
                    <button type="submit">Sign Up</button>
                </div>
                <div class="error">
                    <h4>{{ error }}</h4>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

managment/templates/manag/create.html
{% extends 'base.html' %}
{% block content %}
<h3>Create</h3>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Next</button>
</form>
{% endblock %}

managment/templates/manag/history.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div>        
        <h3>
            history
        </h3>
    </div>
    <div>
        <a href="{% url 'patient_view' %}">Treatment</a>
    </div>
</div>

<div class="container">
    {% for i in data %}
        {{ i.add_history }}<br>
    {% endfor %}
    <br>
    <form method="POST">
        {% csrf_token %}
        <textarea name="add_history" placeholder="Eneter History" cols="135" rows="10" id="id_add_history" autocapitalize="none" autocomplete="add_history" autofocus="" required="" ></textarea>
        <br>
        <button>Submit</button>
    </form>
</div>
{% endblock %}

managment/templates/manag/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container srch">
  <form method="POST" action="/search/">
  {% csrf_token %}
      <input type="text" name="srch" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username">
      <button>Search</button>
  </form>
</div>
<div class="container txt">
  
    <h2>Welcome To <b>HomeoPathic</b> Hospital Managment Sysyetm</h2>
  
  <p>
      <b>If there is new patient then it need to be SignIn else go through login enter <br>credential and see patient view </b>
  </p>
</div>

{% endblock %}

managment/templates/manag/patient_view.html
{% extends 'base.html' %}
{% block content %}
<div class="container"> 
    <div class="row P_hdr">
        <div class="col-md-4">
            <h3>patient view</h3> 
        </div>
        <div class="col-md-8 " style="padding-left:50%;">
            {% for i in data %}
            <p><svg width="2em" height="1.5em" viewBox="0 0 16 16" class="bi bi-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
            </svg></i>&nbsp;{{ i.name }}</p>
          {% endfor %}
          <a href="{% url 'history' %}">History</a>
        </div>
    </div>

    <div>
        <h4>Previous Treatments</h4>
        {% for i in trt %}
        <li>{{ i.created_at }} &nbsp {{ i.add_treat }}</li><br>
        {% endfor %}
    </div>
    

    <div class="txtbox"> 
        <h4>Enter Treatment</h4>
        <form method="POST">
            {% csrf_token %}
            <textarea name="add_treat" cols="135" placeholder="Enter Treatment" rows="10" id="id_add_treat"></textarea>
            <button>Add_Treatment</button>
        </form>
    </div>
</div>

{% endblock %}

managment/templates/manag/search.html
{% extends 'base.html' %}
{% block content %}
    <div class="container srch">
        <form method="POST" action="/search/">
        {% csrf_token %}
            <input type="text" name="srch" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username">
            <button>Search</button>
        </form>
    </div>
    <div class="container">
        {% for srh in sr.all %}
            <a href="{% url 'loginuser' %}">
                {{ srh.id }}&nbsp;&nbsp;
                {{ srh.name }}&nbsp;&nbsp;
                {{ srh.age }}&nbsp;&nbsp;
                {{ srh.address }}&nbsp;&nbsp;
                {{ srh.email }}&nbsp;&nbsp;
                {{ srh.phone }}
            </a> <br>
        {% endfor %}
        {% if messages %}
            {% for k in messages %}
                {{k}}
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}